import Head from "next/head";
import Image from "next/image";

const OurClients = () => {
  return (
    <>
      <Head>
        <title>Clients | Spotlight Media</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* Full Screen Header */}
      <div className="relative z-0 w-full pt-24 text-white bg-cover bg-home-header">
        {/* Hero Text Wrapper */}
        <div className="z-20 flex flex-col items-start justify-center py-12">
          <div className="container z-20 mx-auto motion-safe:animate-fadeSlideUp">
            <h6 className="z-20 font-normal tracking-wider text-left text-gray-500 uppercase">
              Who We Work With
            </h6>

            <h1 className="z-20 w-4/5 mb-0 leading-tight text-left text-white">
              Clients
            </h1>
          </div>
        </div>
      </div>

      {/* Our Clients Section */}
      <div className="relative w-full bg-gray-white">
        <div className="container py-16 mx-auto text-left">
          <div className="flex flex-col items-center">
            <div className="flex flex-col w-full mr-4 text-left">
              <h4 className="mb-4">
                We work with some of the UK’s biggest companies and independent
                contractors.
              </h4>
              <p className="leading-8">
                We have bases in Bristol, Birmingham and Brighton, and work
                across the UK with clients both big and small.
              </p>
              <p className="leading-8">
                If you’re interested in working with us then please feel free to
                give us a call today, or email us, and we’ll get back to you to
                discuss your project.
              </p>
              <p className="leading-8">
                After your free consultation with a member of our team, we’ll
                put together a no-obligation quote and take it from there!
              </p>
            </div>
          </div>
        </div>

        {/* Client Logos Section */}
        <div className="container mx-auto">
          <div className="container px-4 py-8 mx-auto mb-24 text-left bg-gray-100 border border-gray-200 rounded-md">
            <div className="flex flex-wrap w-full mr-4">
              <div className="w-1/2 opacity-60 md:w-1/3 lg:w-1/6 hover:opacity-100">
                <Image
                  src="/client-logo-2.png"
                  width={376}
                  height={160}
                  alt="Landpoint Gardens logo"
                />
              </div>
              <div className="w-1/2 md:w-1/3 lg:w-1/6 opacity-60 hover:opacity-100">
                <Image
                  src="/client-logo-1.png"
                  width={376}
                  height={160}
                  alt="Willmott Dixon logo"
                />
              </div>
              <div className="w-1/2 md:w-1/3 lg:w-1/6 opacity-60 hover:opacity-100">
                <Image
                  src="/client-logo-3.png"
                  width={376}
                  height={160}
                  alt="NHS logo"
                />
              </div>
              <div className="w-1/2 md:w-1/3 lg:w-1/6 opacity-60 hover:opacity-100">
                <Image
                  src="/client-logo-4.png"
                  width={376}
                  height={160}
                  alt="Merlin Housing logo"
                />
              </div>
              <div className="w-1/2 md:w-1/3 lg:w-1/6 opacity-60 hover:opacity-100">
                <Image
                  src="/client-logo-5.png"
                  width={376}
                  height={160}
                  alt="Birmingham City Crane Hire logo"
                />
              </div>
              <div className="w-1/2 md:w-1/3 lg:w-1/6 opacity-60 hover:opacity-100">
                <Image
                  src="/client-logo-6.png"
                  width={376}
                  height={160}
                  alt="Jamesons Tyre Company logo"
                />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Let's Work Together Section */}
      <div className="relative w-full bg-gray-100">
        <div className="container py-20 mx-auto text-left">
          <h2 className="mb-8 text-black">Let's work together</h2>
          <p className="mb-8 text-lg leading-loose text-black">
            We're always interested in working on new and exciting projects.
            <br />
            Get in touch with our team and let's discuss yours today
          </p>
          <button className="mr-4 btn-yellow-2">Contact us</button>
        </div>
      </div>
    </>
  );
};

export default OurClients;
