import Head from 'next/head'
import React, { useState, useRef } from 'react';

const Contact = () => {

    const inputElement = useRef(null);

    const [status, setStatus] = useState("Submit");
    const [success, setSuccess] = useState(null);

    const handleSubmit = async (e) => {
        e.preventDefault();
        setStatus("Sending...");
        const { name, email, message } = e.target.elements;
        let details = {
        name: name.value,
        email: email.value,
        message: message.value,
        };
        let response = await fetch("http://localhost:5000/contact", {
        method: "POST",
        headers: {
            "Content-Type": "application/json;charset=utf-8",
        },
        body: JSON.stringify(details),
        });
        setStatus("Submit");
        let result = await response.json();
        alert(result.status);
        setSuccess("Your form has been submitted");
        name.value = "";
        email.value = "";
        message.value = "";
    };

    return (
        <>

        <Head>
        <title>Contact | Spotlight Media</title>
        <meta name="description" content="Generated by create next app" />
        </Head>

        {/* Full Screen Header */}
        <div className="relative bg-home-header bg-cover text-white w-full z-0 pt-24">
            
            {/* Overlay */}
            <div className="absolute w-full h-36 md:h-60 bg-black opacity-50 z-0">
            </div>

            {/* Hero Text Wrapper */}
            <div className="flex flex-col items-start z-20 h-36 md:h-60 justify-center">

                <div className="container mx-auto z-20 motion-safe:animate-fadeSlideUp">
                    <h6 className="tracking-wider text-gray-500 text-left uppercase font-normal z-20">
                    Let's discuss your project
                    </h6>

                    <h1 className="w-4/5 leading-tight text-white text-left z-20">
                    Contact
                    </h1>
                </div>

            </div>

        </div>
        
        {/* Contact Form */}
        
        <div className="relative bg-white w-full">
            <div className="container mx-auto py-16 text-left">

            <div className="flex items-start flex-col md:flex-row">
                
                <div className="w-full md:w-2/3 mr-8 text-left flex-col flex">

                <h3 className="mb-8">Send us a Message</h3>
                
                { success ? ( 
                <div className="p-4 bg-gray-100 border-2 border-gray-200 mb-8">
                Thanks for the message! We'll get back to you as soon as possible (usually within 12 hours!).
                </div>
                ) : ( <></> ) }

                <form onSubmit={handleSubmit}>
                    <div className="mb-2 flex">
                        <div className="mr-2">
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" /></svg>
                        </div>
                        <div className="flex-grow">
                        <label htmlFor="name">Name:</label>
                        </div>
                    </div>
                    <input
                        type="text"
                        id="name"
                        placeholder="John Smith"
                        ref={inputElement}
                        className="mt-2 mb-8" 
                        required
                    />

                    <div className="mb-2 flex">
                        <div className="mr-2">
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207" /></svg>
                        </div>
                        <div className="flex-grow">
                        <label htmlFor="email">Email:</label>
                        </div>
                    </div>
                    <input type="email" id="email" placeholder="john@smith.com" required className="mt-2 mb-8" />

                    <div className="mb-2 flex">
                        <div className="mr-2">
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" /></svg>
                        </div>
                        <div className="flex-grow">
                        <label htmlFor="message">Message:</label>
                        </div>
                    </div>
                    <textarea id="message" required className="mt-2" />
                    <button type="submit" className="btn-yellow-2 mt-4">{status}</button>
                </form>

                    {/* <form>
                    <div class="mb-4">
                        <label class="block text-md font-light mb-2" for="username">Username</label>
                        <input type="text" name="username" id="" placeholder="Username" />
                    </div>
                    <div class="mb-4">
                        <label class="block text-md font-light mb-2" for="password">Password</label>
                        <input type="password" name="password" id="" placeholder="Password" />
                    </div>

                    <div class="flex items-center justify-between mb-5">
                        <button class="bg-indigo-600 hover:bg-blue-700 text-white font-light py-2 px-6 rounded focus:outline-none focus:shadow-outline" type="button">
                        LOGIN
                        </button>
                        <a class="inline-block align-baseline font-light text-sm text-indigo-600 hover:text-indigo-500" href="#">
                        Forgot Password?
                        </a>
                    </div>
                    <p class="text-center text-md font-light">Don't have an account? <a class="font-light text-md text-indigo-600">Create</a></p>
                    </form> */}

                </div>

                <div className="w-full md:w-1/3 mt-16 md:mt-0">

                    <h3 className="mb-8">Our Details</h3>

                    <div className="flex mb-4">
                    <div className="text-gray-600 mr-2">
                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" /></svg>
                    </div>
                    <p className="text-gray-600 mb-4">
                    <a href={`mailto:info@wearespotlight.co.uk`} className="mb-4 text-gray-600 transition-colors duration-500 hover:text-black">info@wearespotlight.co.uk</a>
                    </p>
                    </div>

                    <div className="flex mb-4">
                    <div className="text-gray-600 mr-2">
                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" /></svg>
                    </div>
                    <p className="text-gray-600 mb-4">
                    <a href={`tel:+447717131511`} className="mb-4 text-gray-600 transition-colors duration-500 hover:text-black">07717 131 511</a>
                    </p>
                    </div>

                    <div className="flex mb-4">
                    <div className="text-gray-600 mr-2">
                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
                    </div>
                        <div className="flex flex-col">
                        <p className="mb-2">104 Wrington Close,</p>
                        <p className="mb-2">Little Stoke,</p>
                        <p className="mb-2">Bristol</p>
                        <p className="mb-2">BS34 6ET</p>
                        </div>
                    </div>
                
                </div>

            </div>

            </div>
        </div>


        </>
    )
}

export default Contact;