import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home = () => {
  return (
    <div className="relative flex flex-col items-center bg-white App">
      <Head>
        <title>Spotlight Media | Construction, Property & Trades</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* Full Screen Header */}
      <div className="relative z-0 w-full h-screen text-white bg-cover bg-home-header">
        {/* Overlay */}
        <div className="absolute z-0 w-full h-screen bg-black opacity-50"></div>

        {/* Container for Arrow */}
        <div className="absolute z-0 flex flex-col items-center justify-end w-full h-screen pb-6 opacity-100">
          {/* Downwards Arrow */}
          <div className="mt-auto text-yellow animate-bounce">
            <svg
              className="w-6 h-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M19 13l-7 7-7-7m14-8l-7 7-7-7"
              />
            </svg>
          </div>
        </div>

        {/* Hero Text Wrapper */}
        <div className="z-20 flex flex-col items-center justify-center flex-1 h-screen pt-12">
          <h1 className="z-20 w-4/5 leading-tight text-center text-white motion-safe:animate-fadeSlideUp">
            We create content for the <em className="em">construction</em>,{" "}
            <em className="em">property</em> and <em className="em">trades</em>{" "}
            industries.
          </h1>

          <div className="flex mt-8 motion-safe:animate-fadeSlideUp">
            <Link href="/contact">
              <a className="mr-4 btn-yellow">Contact us</a>
            </Link>

            <Link href="/who-we-are">
              <a className="btn-gray-outline">Learn More</a>
            </Link>
          </div>
        </div>
      </div>

      {/* What We Do Section */}
      <div className="relative w-full bg-white js-show-on-scroll">
        <div className="container py-20 mx-auto text-center">
          <h2 className="mb-8">What we do</h2>
          <p className="text-lg font-bold">
            We create media for the construction, property and trades
            industries.
          </p>
          <p className="mb-12 text-lg">
            We've been videography, web and design services to corporate clients
            across Bristol, Birmingham and Brighton since 2019.
          </p>

          <div className="flex flex-col items-start md:flex-row">
            <div className="flex flex-col w-full mb-8 mr-4 text-center md:w-1/3 md:mb-0">
              {/* Icon */}
              <div className="w-1/5 mx-auto mb-4 transition duration-500 ease-in-out transform md:w-1/3 hover:scale-110">
                <Image src="/service-icon-1.svg" width={270} height={250} />
              </div>
              {/* Content */}
              <div>
                <div className="flex items-center justify-center h-auto mb-4 md:h-16 lg:h-auto md:mb-0 lg:mb-4">
                  <h4 className="mb-0">Video Production</h4>
                </div>
                <p className="leading-2">
                  We produce quality content from location tours to training
                  videos.
                </p>
              </div>
            </div>

            <div className="flex flex-col w-full mb-8 mr-4 text-center md:w-1/3 md:mb-0">
              {/* Icon */}
              <div className="w-1/5 mx-auto mb-4 transition duration-500 ease-in-out transform md:w-1/3 hover:scale-110">
                <Image src="/service-icon-2.svg" width={270} height={250} />
              </div>
              {/* Content */}
              <div>
                <div className="flex items-center justify-center h-auto mb-4 md:h-16 lg:h-auto md:mb-0 lg:mb-4">
                  <h4 className="mb-0">Web Development</h4>
                </div>
                <p className="leading-2">
                  We design and build fast and functional websites.
                </p>
              </div>
            </div>

            <div className="flex flex-col w-full mb-8 mr-4 text-center md:w-1/3 md:mb-0">
              {/* Icon */}
              <div className="w-1/5 mx-auto mb-4 transition duration-500 ease-in-out transform md:w-1/3 hover:scale-110">
                <Image src="/service-icon-3.svg" width={270} height={250} />
              </div>
              {/* Content */}
              <div>
                <div className="flex items-center justify-center h-auto mb-4 md:h-16 lg:h-auto md:mb-0 lg:mb-4">
                  <h4 className="mb-0">Design & Branding</h4>
                </div>
                <p className="leading-2">
                  We offer a comprehensive digital and print design service.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Who we work with Section */}
      <div className="relative w-full bg-yellow">
        <div className="container py-20 mx-auto text-center">
          <h2 className="mb-8">Who we work with</h2>
          <p className="mb-12 text-lg font-normal">
            We work with clients nationwide, including some of the UK’s largest
            companies and independent contractors.
          </p>

          <div className="flex flex-row flex-wrap items-center">
            <div className="w-1/2 sm:w-1/3 lg:w-1/6">
              <Image src="/client-logo-1.png" width={376} height={160} />
            </div>

            <div className="w-1/2 sm:w-1/3 lg:w-1/6">
              <Image src="/client-logo-2.png" width={376} height={160} />
            </div>

            <div className="w-1/2 sm:w-1/3 lg:w-1/6">
              <Image src="/client-logo-3.png" width={376} height={160} />
            </div>

            <div className="w-1/2 sm:w-1/3 lg:w-1/6">
              <Image src="/client-logo-4.png" width={376} height={160} />
            </div>

            <div className="w-1/2 sm:w-1/3 lg:w-1/6">
              <Image src="/client-logo-5.png" width={376} height={160} />
            </div>

            <div className="w-1/2 sm:w-1/3 lg:w-1/6">
              <Image src="/client-logo-6.png" width={376} height={160} />
            </div>
          </div>
        </div>
      </div>

      {/* Let's Work Together Section */}
      <div className="relative w-full bg-gray-900">
        <div className="container py-20 mx-auto text-center">
          <h2 className="mb-8 text-white">Let's work together</h2>
          <p className="mb-8 text-lg text-white">
            We're always interested in working on new and exciting projects. Get
            in touch with our team and let's discuss yours today
          </p>
          <button className="mr-4 btn-yellow">Contact us</button>
        </div>
      </div>
    </div>
  );
};

export default Home;
