import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Animated from "react-mount-animation";

import VideoServices from "../components/VideoServices";
import WebServices from "../components/WebServices";
import DesignServices from "../components/DesignServices";

const WhatWeDo = () => {
  const [showVideo, setShowVideo] = useState(true);
  const [showWeb, setShowWeb] = useState(false);
  const [showDesign, setShowDesign] = useState(false);

  const mountAnimation1 = `
    0% {opacity: 0}
    30% {opacity: 0}
    100% {opacity: 1}
    `;
  const handleVideoContent = (e) => {
    e.preventDefault();
    setShowWeb(false);
    setShowDesign(false);
    setShowVideo(true);
  };

  const handleWebContent = (e) => {
    e.preventDefault();
    setShowVideo(false);
    setShowDesign(false);
    setShowWeb(true);
  };

  const handleDesignContent = (e) => {
    e.preventDefault();
    setShowVideo(false);
    setShowWeb(false);
    setShowDesign(true);
  };

  return (
    <>
      <Head>
        <title>What We Do | Spotlight Media</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* Full Screen Header */}
      <div className="relative z-0 w-full pt-24 text-white bg-cover bg-home-header">
        {/* Hero Text Wrapper */}
        <div className="z-20 flex flex-col items-start justify-center py-12">
          <div className="container z-20 mx-auto motion-safe:animate-fadeSlideUp">
            <h6 className="z-20 mb-0 font-normal tracking-wider text-left text-gray-500 uppercase">
              Our Work
            </h6>

            <h1 className="z-20 w-4/5 mb-0 leading-tight text-left text-white">
              What we do
            </h1>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="relative w-full bg-white">
        <div className="container flex flex-col py-16 mx-auto">
          <p className="mb-8 text-xl">
            We offer a great range of services across video production, web
            development and design.
          </p>

          <div className="flex w-full bg-white border-0">
            <a
              href="#"
              onClick={handleVideoContent}
              className={`flex items-center w-1/3 transition-all duration-500  ease-in-out p-4 border-2 border-white text-center ${
                showVideo ? "bg-yellow" : "bg-gray-200"
              } `}
            >
              {/* Video Title */}
              <p className="mx-auto mb-0 text-base font-bold tracking-tight md:text-xl">
                Video Production
              </p>
            </a>

            <a
              href="#"
              onClick={handleWebContent}
              className={`flex items-center w-1/3 transition-all duration-500 p-4 border-2 border-white text-center ${
                showWeb ? "bg-yellow" : "bg-gray-200"
              } `}
            >
              {/* Web Title */}
              <p className="mx-auto mb-0 text-base font-bold tracking-tight md:text-xl">
                Web Development
              </p>
            </a>

            <a
              href="#"
              onClick={handleDesignContent}
              className={`flex items-center w-1/3 transition-all duration-500 p-4 border-2 border-white text-center ${
                showDesign ? "bg-yellow" : "bg-gray-200"
              } `}
            >
              {/* Design Title */}
              <p className="mx-auto mb-0 text-base font-bold tracking-tight md:text-xl">
                Design & Branding
              </p>
            </a>
          </div>

          <div className="flex w-full">
            {showVideo ? (
              <Animated.div
                key={1}
                show={showVideo.toString()}
                mountAnim={mountAnimation1}
                time={1.1}
              >
                <VideoServices />
              </Animated.div>
            ) : showWeb ? (
              <Animated.div
                key={2}
                show={showWeb.toString()}
                mountAnim={mountAnimation1}
                time={1.1}
              >
                <WebServices />
              </Animated.div>
            ) : showDesign ? (
              <Animated.div
                key={3}
                show={showDesign.toString()}
                mountAnim={mountAnimation1}
                time={1.1}
              >
                <DesignServices />
              </Animated.div>
            ) : null}
          </div>
        </div>
      </div>

      {/* Let's Work Together Section */}
      <div className="relative w-full bg-gray-100">
        <div className="container py-20 mx-auto text-left">
          <h2 className="mb-8 text-black">Let's work together</h2>
          <p className="mb-8 text-lg text-black">
            We're always interested in working on new and exciting projects. Get
            in touch with our team and let's discuss yours today
          </p>
          <button className="mr-4 btn-yellow-2">Contact us</button>
        </div>
      </div>
    </>
  );
};

export default WhatWeDo;
