import Head from 'next/head';
import Image from 'next/image';

const WhatWeDo = () => {
    return (
        <>
        <Head>
        <title>What We Do | Spotlight Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* Full Screen Header */}
        <div className="relative bg-home-header bg-cover text-white w-full z-0 pt-24">
            
            {/* Overlay */}
            <div className="absolute w-full h-96 bg-black opacity-50 z-0">
            </div>

            {/* Hero Text Wrapper */}
            <div className="flex flex-col items-start z-20 h-96 justify-end pb-16">

            <div className="container mx-auto z-20 motion-safe:animate-fadeSlideUp">
                <h6 className="tracking-wider text-yellow text-left uppercase font-normal z-20">
                What We Do
                </h6>

                <h1 className="w-4/5 leading-tight text-white text-left z-20">
                We create compelling content
                </h1>
            </div>

            </div>
        </div>
        
        {/* Video Services Header */}
        
        <div className="relative bg-gray-100 w-full">
            <div className="container mx-auto py-20 text-left flex">

                <div className="w-1/3 flex flex-col items-start">

                    {/* Promotional videos */}
                    <div className="w-full mr-8 flex flex-col">
                        
                    <div className="w-1/6 mr-auto flex flex-col mb-8">
                    <Image
                        src="/service-icon-1.svg"
                        alt="Service"
                        width={270}
                        height={250}
                    />
                    </div>

                    <h5 className="mb-4">Promotional Videos</h5>

                    <p className="mb-4">Our promotional video service will not only show your company or business in the best light, but also helps build brand awareness. We make sure the concept behind your video will captivate your audience, drive leads and boost sales.</p>
                    </div>

                    {/* Corporate communications */}
                    <div className="w-full mr-8 flex flex-col">
                        
                    <div className="w-1/5 mr-auto flex flex-col mb-8">
                    <Image
                        src="/service-icon-2.svg"
                        alt="Service"
                        width={270}
                        height={250}
                    />
                    </div>

                    <h5 className="mb-4">Corporate Communications</h5>

                    <p className="mb-4">Our communications videos make it simple for you to communicate with your staff - or send important messages - in a consistent manner. We ensure all content is in-fitting with brand guidelines and expectations.</p>
                        
                    </div>

                    {/* Customer testimonials */}
                    <div className="w-full mr-8 flex flex-col">
                        
                    <div className="w-1/5 mr-auto flex flex-col mb-8">
                    <Image
                        src="/service-icon-3.svg"
                        alt="Service"
                        width={270}
                        height={250}
                    />
                    </div>

                    <h5 className="mb-4">Customer Testimonials</h5>

                    <p className="mb-4">Let your happy customers sell your services with customer testimonial videos. These help you stand out from your competitors, give your company character, and build long-lasting relationships with your customer base.</p>

                    </div>

                </div>

            </div>
        </div>

        </>
    )
}

export default WhatWeDo;