import React, { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Animated from "react-mount-animation";

import VideoServices from '../components/VideoServices';
import WebServices from '../components/WebServices';
import DesignServices from '../components/DesignServices';

const WhatWeDo = () => {

    const [showVideo, setShowVideo] = useState(true);
    const [showWeb, setShowWeb] = useState(false);
    const [showDesign, setShowDesign] = useState(false);

    const mountAnimation1 = `
    0% {opacity: 0}
    50% {opacity: 0}
    100% {opacity: 1}
    `;
    const handleVideoContent = (e) => {
        e.preventDefault();
        setShowWeb(false);
        setShowDesign(false);
        setShowVideo(true);
    }
    
    const handleWebContent = (e) => {
        e.preventDefault();
        setShowVideo(false);
        setShowDesign(false);
        setShowWeb(true);
    }

    const handleDesignContent = (e) => {
        e.preventDefault();
        setShowVideo(false);
        setShowWeb(false);
        setShowDesign(true);
    }

    return (
        <>
        <Head>
        <title>What We Do | Spotlight Media</title>
        <meta name="description" content="Generated by create next app" />
        </Head>

        {/* Full Screen Header */}
        <div className="relative bg-home-header bg-cover text-white w-full z-0 pt-24">
            
            {/* Overlay */}
            <div className="absolute w-full h-36 md:h-60 bg-black opacity-50 z-0">
            </div>

            {/* Hero Text Wrapper */}
            <div className="flex flex-col items-start z-20 h-36 md:h-60 justify-center">

            <div className="container mx-auto z-20 motion-safe:animate-fadeSlideUp">
                <h6 className="tracking-wider text-gray-500 text-left uppercase font-normal z-20">
                Our Work
                </h6>

                <h1 className="w-4/5 leading-tight text-white text-left z-20">
                What we do
                </h1>
            </div>

            </div>
        </div>
        
        {/* Content */}
        <div className="relative bg-white w-full">
            <div className="container mx-auto py-16 flex flex-col">

                <div className="flex w-full bg-white border-0">

                    <a href="#" onClick={handleVideoContent} className={`flex items-center w-1/3 transition-all duration-500 p-4 border-2 border-white text-center ${(showVideo) ? 'bg-yellow' : 'bg-gray-200'} `}>
                        {/* Video Title */}
                        <p className="mb-0 mx-auto font-bold text-base md:text-xl tracking-tight">Video Production</p>
                    </a>

                    <a href="#" onClick={handleWebContent} className={`flex items-center w-1/3 transition-all duration-500 p-4 border-2 border-white text-center ${(showWeb) ? 'bg-yellow' : 'bg-gray-200'} `}>
                        {/* Web Title */}
                        <p className="mb-0 mx-auto font-bold text-base md:text-xl tracking-tight">Web Development</p>
                    </a>

                    <a href="#" onClick={handleDesignContent} className={`flex items-center w-1/3 transition-all duration-500 p-4 border-2 border-white text-center ${(showDesign) ? 'bg-yellow' : 'bg-gray-200'} `}>
                        {/* Design Title */}
                        <p className="mb-0 mx-auto font-bold text-base md:text-xl tracking-tight">Design & Branding</p>
                    </a>

                </div>

                <div className="flex w-full">

                    { showVideo ? (

                    <Animated.div
                    key={1}
                    show={showVideo}
                    mountAnim={mountAnimation1}
                    delay={1}
                    time={1.1}
                    >
                        <VideoServices />
                    </Animated.div>

                    ) : showWeb ? (

                    <Animated.div
                    key={2}
                    show={showWeb}
                    mountAnim={mountAnimation1}
                    delay={1}
                    time={1.1}
                    >
                        <WebServices />
                    </Animated.div>

                    ) : showDesign ? (

                    <Animated.div
                    key={3}
                    show={showDesign}
                    mountAnim={mountAnimation1}
                    delay={1}
                    time={1.1}
                    >
                        <DesignServices />
                    </Animated.div>

                    ) : (
                        null
                    )
                    }

                </div>
                
            </div>
        </div>
        
        {/* Let's Work Together Section */}
        <div className="relative bg-gray-100 w-full">
          <div className="container mx-auto py-20 text-left">
          <h2 className="text-black mb-8">Let's work together</h2>
          <p className="text-black text-lg mb-8">We're always interested in working on new and exciting projects. Get in touch with our team and let's discuss yours today</p>
          <button className="btn-yellow-2 mr-4">Contact us</button>
          </div>
        </div>
        </>
    )
}

export default WhatWeDo;